import type { Metadata } from "next";
import { AppProvider } from "./provider";
import { dehydrate, HydrationBoundary, QueryClient } from "@tanstack/react-query";
import { getUserQueryOptions } from "@/lib/auth";
import { ReactNode } from 'react';
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import { theme } from "@/lib/theme";
import "./globals.css";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const RootLayout = async ({ children }: { children: ReactNode }) => {
  
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(getUserQueryOptions());
  const dehydratedState = dehydrate(queryClient);

  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            <AppProvider>
              <HydrationBoundary state={dehydratedState}>
                {children}
              </HydrationBoundary>
            </AppProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
       
      </body>
    </html>
  );
};

export default RootLayout;
